 python/fly_crossy/checkpoint.py                 |  10 [32m+[m[31m-[m
 python/fly_crossy/dev_server.py                 |  10 [32m+[m[31m-[m
 python/fly_crossy/env.py                        |  18 [32m+[m[31m-[m
 python/fly_crossy/export.py                     |   9 [32m+[m[31m-[m
 python/fly_crossy/protocol.py                   |   2 [32m+[m[31m-[m
 python/fly_crossy/runtime_controller.py         |  12 [32m+[m[31m-[m
 python/fly_crossy/schema.py                     |  23 [32m+[m[31m-[m
 python/fly_crossy/train.py                      | 267 [32m+++++++++++++++++++++++[m[31m-[m
 python/tests/test_checkpoint.py                 |  35 [32m+++[m[31m-[m
 python/tests/test_dev_server.py                 |   6 [32m+[m[31m-[m
 python/tests/test_env.py                        |   4 [32m+[m[31m-[m
 python/tests/test_export.py                     |   2 [32m+[m[31m-[m
 python/tests/test_nested_connectome.py          |   2 [32m+[m[31m-[m
 python/tests/test_nested_feedback_connectome.py |   2 [32m+[m[31m-[m
 python/tests/test_nested_gated_connectome.py    |   2 [32m+[m[31m-[m
 python/tests/test_population_interface.py       |   2 [32m+[m[31m-[m
 python/tests/test_protocol.py                   |   2 [32m+[m[31m-[m
 python/tests/test_runtime_controller.py         |  22 [32m+[m[31m-[m
 python/tests/test_schema.py                     |  44 [32m++[m[31m--[m
 python/tests/test_server.py                     |   2 [32m+[m[31m-[m
 python/tests/test_session.py                    |   2 [32m+[m[31m-[m
 python/tests/test_v8_contract.py                | 159 [31m--------------[m
 scripts/generate-environment-parity.mjs         |   2 [32m+[m[31m-[m
 src/App.tsx                                     |   6 [32m+[m[31m-[m
 src/game/controllers.ts                         |   2 [32m+[m[31m-[m
 src/game/model.ts                               |  17 [32m+[m[31m-[m
 src/game/observation.ts                         |  39 [32m+++[m[31m-[m
 src/game/world.ts                               |   2 [32m+[m[31m-[m
 src/hooks/useGame.ts                            |  22 [32m+[m[31m-[m
 src/simulation/client.ts                        |   4 [32m+[m[31m-[m
 tests/fixtures/environment-parity-v2.json       |  30 [32m+[m[31m--[m
 tests/game-controller.test.mjs                  | 128 [32m+++++++++++[m[31m-[m
 tests/game-model.test.mjs                       |   8 [32m+[m[31m-[m
 tests/game-v8-contract.test.mjs                 | 105 [31m----------[m
 tests/game-world.test.mjs                       |   2 [32m+[m[31m-[m
 tests/simulation-client.test.mjs                |  18 [32m+[m[31m-[m
 36 files changed, 634 insertions(+), 388 deletions(-)
